BOARD = zcu104
UBOOT_CONFIG = zcu104
BOARD_MODEL = xilinx.com:zcu104:part0:1.1
PART = xczu7ev-ffvc1156-2-e
#TOP_MODULE_PROJECT = zynq
#CONFIG = ZynqFPGAConfig
TOP_MODULE_PROJECT = zynq.boom
CONFIG ?= SmallBoomZynqConfig
#CONFIG ?= MediumBoomZynqConfigZCU104

include ../common/Makefrag
