create_clock -add -name SYSCLK_125_P -period 8.000 -waveform {0.000 4.000} [get_ports SYSCLK_125_P]

set_property PACKAGE_PIN E23      [get_ports SYSCLK_125_N]
set_property IOSTANDARD  LVDS     [get_ports SYSCLK_125_N]
set_property PACKAGE_PIN F23      [get_ports SYSCLK_125_P]
set_property IOSTANDARD  LVDS     [get_ports SYSCLK_125_P]

set_property PACKAGE_PIN M11      [get_ports i_cpu_reset]
set_property IOSTANDARD  LVCMOS33 [get_ports i_cpu_reset]

set_property PACKAGE_PIN B4       [get_ports i_gpio_pushbutton[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_pushbutton[0]]
set_property PACKAGE_PIN C4       [get_ports i_gpio_pushbutton[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_pushbutton[1]]
set_property PACKAGE_PIN B3       [get_ports i_gpio_pushbutton[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_pushbutton[2]]
set_property PACKAGE_PIN C3       [get_ports i_gpio_pushbutton[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_pushbutton[3]]

set_property PACKAGE_PIN F4       [get_ports i_gpio_dipswitch[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_dipswitch[3]]
set_property PACKAGE_PIN F5       [get_ports i_gpio_dipswitch[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_dipswitch[2]]
set_property PACKAGE_PIN D4       [get_ports i_gpio_dipswitch[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_dipswitch[1]]
set_property PACKAGE_PIN E4       [get_ports i_gpio_dipswitch[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports i_gpio_dipswitch[0]]

set_property PACKAGE_PIN D5       [get_ports o_gpio_led[0]]
set_property IOSTANDARD  LVCMOS33 [get_ports o_gpio_led[0]]
set_property PACKAGE_PIN D6       [get_ports o_gpio_led[1]]
set_property IOSTANDARD  LVCMOS33 [get_ports o_gpio_led[1]]
set_property PACKAGE_PIN A5       [get_ports o_gpio_led[2]]
set_property IOSTANDARD  LVCMOS33 [get_ports o_gpio_led[2]]
set_property PACKAGE_PIN B5       [get_ports o_gpio_led[3]]
set_property IOSTANDARD  LVCMOS33 [get_ports o_gpio_led[3]]
